#!/bin/bash

XORG_PREFIX="$HOME/lib/Xorg"
XORG_CONFIG="--prefix=$XORG_PREFIX --sysconfdir=$XORG_PREFIX/etc --localstatedir=$XORG_PREFIX/var --disable-static"
#XORG_CONFIG="--prefix=$XORG_PREFIX --sysconfdir=/etc --localstatedir=/var --disable-static"
export XORG_PREFIX XORG_CONFIG

PATH=$XORG_PREFIX/bin:$PATH

#PKG_CONFIG_PATH=$XORG_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH
#PKG_CONFIG_PATH=$XORG_PREFIX/share/pkgconfig:$PKG_CONFIG_PATH

#LIBRARY_PATH=$XORG_PREFIX/lib:$LIBRARY_PATH
#C_INCLUDE_PATH=$XORG_PREFIX/include:$C_INCLUDE_PATH
#CPLUS_INCLUDE_PATH=$XORG_PREFIX/include:$CPLUS_INCLUDE_PATH

PKG_CONFIG_PATH=$XORG_PREFIX/lib/pkgconfig
PKG_CONFIG_PATH=$XORG_PREFIX/share/pkgconfig:$PKG_CONFIG_PATH
LIBRARY_PATH=$XORG_PREFIX/lib
C_INCLUDE_PATH=$XORG_PREFIX/include
CPLUS_INCLUDE_PATH=$XORG_PREFIX/include

ACLOCAL='aclocal -I $XORG_PREFIX/share/aclocal'

export PATH PKG_CONFIG_PATH ACLOCAL LIBRARY_PATH C_INCLUDE_PATH CPLUS_INCLUDE_PATH
